### ISSUE TITLE
regression: wmflabs coordinates/links to geo: intent missing

### ISSUE THREAD

**Issue by ce-4** [itkach/aard2-android#105]
A lot of wikipedia articles contain geo references eg. http://tools.wmflabs.org/geohack/geohack.php?params=56.26_N_4.21_W_region:GB_type:country&pagename=Scotland&language=en

Issue https://github.com/itkach/aard2-android/issues/16 requested to have these coordinates available for native apps that consume geo: intents and it was implemented in 2015.

Has this feature been removed or become a regression? I cannot find the button anymore but remember that it was present some (maybe long) time ago.

My use case is privacy awareness and offline use of Aard2 when eg. traveling a foreign big city and reading the relevant places' wikipedia which often have geo coordinate references. I'd like to be able to quickly open a place in native map apps like Osmand. Currently I have to copy the tools.wmflab.org link, extract and paste the coordinates into the map app's search.

**Comment by itkach** [comment]
The link is created when creating/compiling dictionary, it's article content rather than a feature of aard2-android app itself. Maybe Mediawiki changed how geo coordinates are rendered and @itkach/mwscrape2slob code to find it no longer works.

**Comment by itkach** [comment]
Just checked - the link is still there (small globe icon). Checked in English Wikipedia from June 2019 and in test compiled dictionary with freshly scraped few articles. "Scotland" article doesn't seem to have the coordinates for Scotland, but it does for the capital which renders in the infobox next to coordinates text, as expected.

**Comment by ce-4** [comment]
You're right for the english version. German wikipedia seems different (my bad, i wanted to post the scotland article from the german wiki and mistakenly posted the english one):

https://de.m.wikipedia.org/wiki/Schottland

**Comment by ce-4** [comment]
![Screenshot_20200217-210336](https://user-images.githubusercontent.com/1439893/74686730-4caef700-51ca-11ea-9964-b9fd53e91d29.png)

**Comment by ce-4** [comment]
Would it be feasible if Aard2 itself set an intent-filter for http(s)://tools.wmflabs.org/geohack links and then re-emit a geo: intent? That would catch any wmflabs links regardless of the wikipedia css. And one would see the regular Android picker to choose between Browser/Aard2 to handle it. I remember an app that did something this for a third party gaming related maps website to have the location open in the local maps app instead:
https://github.com/marcosdiez/IngressIntelToGps

**Comment by itkach** [comment]
> Would it be feasible if Aard2 itself set an intent-filter for http(s)://tools.wmflabs.org/geohack links and then re-emit a geo: intent?

Maybe, but I would rather not hardcode this very special URL and parsing of its parameters into application. URLs change. This is article content, nothing about it belongs in the app. 

I see that mwscrape2slob is looking for elements with both `geo` and `microformat` and dewiki now produces only `geo`. Looks like it should be ok to widen selector and just look for `geo` (`geo` class is also used in a different way in other wikipedias, but those will be silently ignored since they don't contain elements with classes `latitude` and `longitude`). That will get the "geo:" link back into the article, although it shows up at the bottom of the page and not next to "Koordinaten" because "Koordinaten" now uses absolute position. That is unfortunate implementation on Wikipedia designers part, I don't see a way to workaround that.

**Comment by itkach** [comment]
@MHBraun @ce-4  Fixed in https://github.com/itkach/mwscrape2slob/commit/de164175201111d3ab36b09a6684a2490b5f4429
