### ISSUE TITLE
Doesn't support reading external sdcard on Android 11?

### ISSUE THREAD

**Issue by TuxKruger** [itkach/aard2-android#119]
I have been using Aard 2 for a while now. Worked like a charm till Android 10 but now on Android 11, the app is unable to read external sdcard. I have tried letting the app automatically search for dictionaries like it does on the first run and yes I tried adding manually by clicking the '+' icon. During manually selecting dictionaries, app is unable to read anything under /storage (although it is able to read files under /storage/emulated/0 (internal storage)). I can't find my external sdcard under /mnt either. And yes, everything is fine with external sdcard (other apps can read and write fine).

![aard2](https://user-images.githubusercontent.com/73212487/102508524-7ca97e00-40ab-11eb-901f-e949ddfcac1a.jpg)

![sdcard](https://user-images.githubusercontent.com/73212487/102508547-83d08c00-40ab-11eb-9c69-a4750ca0902c.jpg)

**Device Info:**
- Device: Redmi Note 9S
- Android version: 11
- ROM: AOSP

**Comment by itkach** [comment]
Probably related to [Storage updates in Android 11](https://developer.android.com/about/versions/11/privacy/storage), I'll need to investigate

**Comment by itkach** [comment]
[According to Android docs](https://developer.android.com/training/data-storage/use-cases#opt-out-scoped-storage), apps that target Android 9 (API level 28) or lower are opted out of scoped storage "temporarily" (whatever that means), so everything should work as before, but that doesn't appear to be the case on Android 11. Targeting API level 29 and setting the value of `requestLegacyExternalStorage` to `true` also has no effect on Android 11, as far as I can tell. So it looks like, contrary to documentation, there's actually no way to opt out of the new storage model and scanning or browsing external SD card file-manager style as implemented today is no longer possible - should be replaced with [Storage Access Framework ](https://developer.android.com/training/data-storage/shared/documents-files ) based implementation. This also probably means bumping min sdk version to API Level 19 (Android 4.4)

**Comment by itkach** [comment]
I was wrong, `requestLegacyExternalStorage` set to `true` while targeting API level 29 (which is now minimum for updates to be accepted in Play store) does opt out of scoped storage. The new restriction in Android 11 appears to be that listing content of`/storage` is no longer allowed, but looks like it's possible to hack around that, like so: 89f066feaf8c04ca6fa741476c9fe38176a7e33f. So that's the good news. The bad news is that this opting out of scoped storage will not be possible once applications are forced to target API level 30 (Android 11) and newer, but Storage Access Framework does not provide a way to work with files directly (working with dictionary files requires random access file interface). So unless Google radically improves Storage Access Framework (and it is in dire need of improvement, to put it mildly) no further updates will be publishable to the Play store soon enough.

**Comment by francwalter** [comment]
As I understand, Google is superseding external sdcards since a while (beginning Kitkat).

But for Aard2 does this just mean, that use of dictionaries on internal sdcard will be still possible on API 30+?

**Comment by itkach** [comment]
> But for Aard2 does this just mean, that use of dictionaries on internal sdcard will be still possible on API 30+?

I am not so sure. The goal is to restrict application's access to data/files and always have user authorize such access explicitly at a granular level - this is not really about internal vs external storage, so I wouldn't be surprised if in the future direct file access will only be available with files that application "owns". If that happens then the current implementation won't work at all. The app will have to download dictionaries itself, or allow users to "upload" dictionaries to the app so that dictionary files can be written to that one special application directory Android gives access to, or have users copy files over to that directory on their computer. Or Storage Access Framework could provide proper API, but seeing the sorry state it's in I wouldn't hold my breath.

**Comment by itkach** [comment]
@TuxKruger can you pls test https://github.com/itkach/aard2-android/releases/tag/0.45 and see if it fixes the issue for you?

**Comment by TuxKruger** [comment]
> @TuxKruger can you pls test https://github.com/itkach/aard2-android/releases/tag/0.45 and see if it fixes the issue for you?

@itkach, yeah it fixed the issue, the app is able to read external sdcard.

**Comment by TuxKruger** [comment]
After using the pre-release for 2 days now, I can confirm that this external sdcard issue is fixed, I think I should now close the issue now.
