### ISSUE TITLE
[Feature request] more info about the dictionaries

### ISSUE THREAD

**Issue by MHBraun** [itkach/aard2-android#143]
Within the dictionaries section we can see when using the caret:
- Name of Wikipedia (lang)
- number of items
- copyright
- link to website
- name of file
Would it be possible to add the following parameters to show within the app in the dictionaries section:
mw2slob parameters
- a (author)
- b (binsize)
- c (compression)
- f (filter)
- - namespace(s)

while this may not be relevant for the common user, it is helpful for the author to differentiate different versions of the same file.
or is there any other way to see this information after the slob file is created within the app?

**Comment by itkach** [comment]
- author is displayed (`created.by` tag) when it is set. It needs to be set explicitly either as `mw2slob dump` command line parameter `--created-by` or set later with `slob tag` command, e.g.
```
slob tag -n created.by -v "me (https://aarddict.org)" test.slob
```

- compression is displayed in aard2-web dictionary info or with `slob info`

- other parameters can be added to file name if necessary, like so 
```
COMP=zlib; BINSIZE=1024; mw2slob dump --compression $COMP --bin-size $BINSIZE --siteinfo simple.si.json simplewiki-NS0-20220401-ENTERPRISE-HTML.json.tar.gz --filter wiki common -e 100 -o test.$COMP.b$BINSIZE.slob
```

- dictionary's label can be changed with `slob tag`, e.g.
```slob tag -n label -v "simple wiki zlib 1024 bin" test.slob```
This is probably the easiest way to distinguish two files in UI

Presumably this is only interesting during testing and experimenting with various compilation parameters to compare results, so probably doesn't deserve prominent place in UI for end user. 

Local namespace ids may be interesting to add to enable smarter handling of inter-wiki links (e.g. open local version when corresponding wikipedia namespace content is available locally, otherwise open online version) - but that's another conversation.

**Comment by MHBraun** [comment]
Thank you for the explanation. This is a workaround.
