### ISSUE TITLE
Problem with app permession (Samsung galaxy a31)

### ISSUE THREAD

**Issue by nemko78** [itkach/aard2-android#147]
It is not possible to add dictionaries. inability to give the right to access the file system.
![Screenshot_20220808-014630_Aard 2](https://user-images.githubusercontent.com/62820802/183308611-40da84f2-f9a7-47c7-bf73-db5d675db0c8.png)
![Screenshot_20220808-014634_Permission controller](https://user-images.githubusercontent.com/62820802/183308639-657a8d6f-6b9e-45f7-84e7-515893e4322c.png)

**Comment by itkach** [comment]
Can you describe what happens when you tap the "+" button in more detail? Operating system's File Chooser should pop up. Permission to access specific files is granted implicitly when user selects those files. The application does not (and cannot as of Android 11) have direct access to the file system, so no such permissions are listed. The error message indicates that it's Android system component that does not have access to the given URI. Is it possible that the file is actually not there, perhaps renamed or moved, or a different SD card is used? If so, then re-opening the dictionary from the new location should work. If a 3rd party app is used to open files instead of OS's native File Chooser, try selecting with OS file chooser instead.
