### ISSUE TITLE
V 0.14 slob search

### ISSUE THREAD

**Issue by cyko69** [itkach/aard2-android#17]
APP crashes when manually searching for dictionaries ("find dictionaries")

**Comment by itkach** [comment]
Doesn't crash for me on several devices. Which device do you have, what version of Android? Error from the log would be ideal.

**Comment by cyko69** [comment]
Error Logcat:
E/AndroidRuntime(23022): FATAL EXCEPTION: main
E/AndroidRuntime(23022): Process: itkach.aard2, PID: 23022
E/AndroidRuntime(23022): java.lang.RuntimeException: Dictionary discovery is already running
E/AndroidRuntime(23022):        at itkach.aard2.Application.findDictionaries(Application.java:282)
E/AndroidRuntime(23022):        at itkach.aard2.DictionariesFragment.findDictionaries(DictionariesFragment.java:113)
E/AndroidRuntime(23022):        at itkach.aard2.DictionariesFragment$1.onClick(DictionariesFragment.java:62)
E/AndroidRuntime(23022):        at android.view.View.performClick(View.java:4463)
E/AndroidRuntime(23022):        at android.view.View$PerformClick.run(View.java:18770)
E/AndroidRuntime(23022):        at android.os.Handler.handleCallback(Handler.java:808)
E/AndroidRuntime(23022):        at android.os.Handler.dispatchMessage(Handler.java:103)
E/AndroidRuntime(23022):        at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(23022):        at android.app.ActivityThread.main(ActivityThread.java:5292)
E/AndroidRuntime(23022):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(23022):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(23022):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
E/AndroidRuntime(23022):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
E/AndroidRuntime(23022):        at dalvik.system.NativeStart.main(Native Method)

**Comment by itkach** [comment]
Awesome, thank you. I can now crash it myself like this: while dictionary discovery is running and progress dialog is displayed, tap outside the dialog - this hides the dialog (it shouldn't) - and I can tap "Find Dictionaries" in the tab or in action bar again, which crashes the app because discovery is already running. 

Can you describe in more detail how does it happen for you? If it's just a matter of UI allowing to initiate discovery second time and user double-tapping the button then it's pretty straightforward. It may be a bit more interesting though. When application starts without any dictionaries, Dictionaries tab is activated and dictionary discovery is started automatically. If "Please wait" dialog fails to appear for some reason, it looks like app is doing nothing and if at that moment user taps "Find Dictionaries" the crash will occur. Do you see "Please wait" dialog when app starts initially without any open dictionaries? Does it disappear itself or do you tap the screen?

**Comment by itkach** [comment]
> Cubot X6
Just curious, does it come with Google Play Store installed?

**Comment by cyko69** [comment]
The "Please wait" dialog shows up properly, but i have clicked the back button to stop the ongoing discovery because my SD card has many files and in similar apps the searching takes a long time. So I stopped it to choose a manual directory, but then I though I have the time to let the app search ;) -> crash... 
I think from a users perspective the search should be canceled when he presses "back".
And yes, the X6 comes with preinstalled Playstore.

**Comment by itkach** [comment]
> the search should be canceled when he presses "back".

Indeed. Thank you for the report.

**Comment by itkach** [comment]
Fixed in b409110eabaac7d4d3a25226b05d2f3e96a0f12d
