### ISSUE TITLE
The app crashes when filtering

### ISSUE THREAD

**Issue by liushuqi-2022** [itkach/aard2-android#179]
**To Reproduce**
	1. Go to Bookmarks or History
	2. Click Filter button
	3. App crash during input

**Expected behavior**
The filtering operation is working

**Record**
[crash.webm](https://github.com/itkach/aard2-android/assets/111285450/46200fe9-cf91-4baf-a2f0-3a3ab499b9d6)

**Environment**
Android version: 8.0
Device: pixel XL
App Version: 0.56

**Comment by MHBraun** [comment]
Can confirm on Android 14 with OneUI 6.0


Markus Braun


________________________________
From: liushuqi-2022 ***@***.***>
Sent: Sunday, May 19, 2024 10:53
To: itkach/aard2-android
Cc: Subscribed
Subject: [itkach/aard2-android] The app crashes when filtering (Issue #179)

To Reproduce
1. Go to Bookmarks or History
2. Click Filter button
3. App crash during input
Expected behavior
The filtering operation is working
Record
crash.webm
Environment
Android version: 8.0
Device: pixel XL
App Version: 0.56

**Comment by itkach** [comment]
fixed in https://github.com/itkach/slobj/commit/b7e0abbf0e51525ee28c94e32ac4f8827321e99f
