### ISSUE TITLE
User CSS styling doesn't work...

### ISSUE THREAD

**Issue by Akmal02** [itkach/aard2-android#30]
I'm using Android 4.2.2 on my 4" phone.
It seems that CSS styling doesn't get to work, only the builtin Default and Dark do.
This is what I've done:
1. Goto Aard's setting, then select User Styles
2. It asks me to launch an app, so I choose Jota Text Editor.
3. Write a simple css on the editor
   body {
    background-color: blue;
  }
4. Save as "mytheme.css" and exit from the editor.
5. Found the new entry "mytheme" on dictionary menu, but nothing happens when I click on it.

I've also tried a builtin night css (which I managed to found it in the dictionary itself "~/css/night.css") on Simple Wikipedia. I copy the css and make it as user css, still doesn't work.
Hope you can fix this.
Anyway, a great app.. Thanks.

**Comment by francwalter** [comment]
You need to activate this new style in your wiki.
Open any entry in your wiki and press the menu button. You have a menu "Styles". Here you can choose now your new personal style.
It works on my device with actual aard2, I dont think this is an issue.

**Comment by itkach** [comment]
User styles work for me just fine (Android 4.4, 5.0 and 5.1). 

> 2. It asks me to launch an app, so I choose Jota Text Editor.

It's supposed to be some app that can select a file, such as a file manager (ES File Explorer for example), but Jota Text Editor works fine for me too. I would recommend preparing your css on a desktop computer though, with a CSS syntax aware editor and then copying the file - style may fail to apply due to a syntax error and it's very easy to mess things up when typing or copy-pasting on a phone.

> I'm using Android 4.2.2

None of my devices are running that, I'll need to set up this version in the emulator and investigate.

**Comment by MHBraun** [comment]
@Frank: Do you still have the original rom on your S4? This should be a 4.2.2. Maybe you can give Igor a hand.

My S4 is at 4.4.2 now…

 

 

Von: itkach [mailto:notifications@github.com] 
Gesendet: Donnerstag, 7. Mai 2015 18:11
An: itkach/aard2-android
Betreff: Re: [aard2-android] User CSS styling doesn't work... (#30)

 

User styles work for me just fine (Android 4.4, 5.0 and 5.1). 

1.	It asks me to launch an app, so I choose Jota Text Editor.

It's supposed to be some app that can select a file, such as a file manager (ES File Explorer for example), but Jota Text Editor works fine for me too. I would recommend preparing your css on a desktop computer though, with a CSS syntax aware editor and then copying the file - style may fail to apply due to a syntax error and it's very easy to mess things up when typing or copy-pasting on a phone.

I'm using Android 4.2.2

None of my devices are running that, I'll need to set up this version in the emulator and investigate.

**Comment by itkach** [comment]
I see what's the issue - new lines in css are not properly escaped when used in javascript. WebView component in Android > 4.4 interprets string literal with unescaped new lines without error, even though technically it's not valid, WebView in 4.3 and earlier pukes.

**Comment by itkach** [comment]
Fixed in 6e55e492a97a24279b1634cf35623061f2febdba

Give it a try: https://github.com/itkach/aard2-android/releases/tag/0.20
You'll need to remove your css (in settings) and import it again.

**Comment by francwalter** [comment]
@MarkusB: I have on my SGS4 CM12 (5.0) so could not test. I have no device with < 4.3, sorry.

**Comment by Akmal02** [comment]
CSS working now. Thanks again!
