### ISSUE TITLE
user style addition button & Kiwix

### ISSUE THREAD

**Issue by cosmopol** [itkach/aard2-android#40]
Using the user style addition button (plus sign) shows a Kiwix Zim file selection screen on my e-ink ereader with open Android 4.2.

**Comment by itkach** [comment]
> shows a Kiwix Zim file selection screen

Can you select a non-zim file with it? This uses system file selector, if it happens to be Kiwix and it works that shouldn't be a problem.

**Comment by cosmopol** [comment]
No, I cannot do that. It seems I am given a pre-compiled option of Kiwix zim files found on my ereader device ( it reads: "Select a ZIM Content File (*.zim)" ). It does not allow for any kind of navigation.

PS: nice to meet you

**Comment by itkach** [comment]
I see. It looks like Kiwix is doing the wrong thing here: it tells the OS it can handle general requests from applications to get content while in fact it is not designed for that. aard2 specifically asks for text content and it looks like Kiwix doesn't honor it. Can you install a file manager like for example [ES File Explorer](https://play.google.com/store/apps/details?id=com.estrongs.android.pop) and see if you get a prompt to use it (instead of Kiwix) to select a file?

**Comment by cosmopol** [comment]
ES File Explorer? No, thanks. I do not need all that spyware added. OI File Manager it is for me, with which it works.

**Comment by cosmopol** [comment]
Was that helpful?

**Comment by itkach** [comment]
It just confirms that Kiwix is wrong. There's nothing for me to fix here.

**Comment by itkach** [comment]
The app has it's own file selector which could be used instead, however this would result in reduced functionality. Using OS implementation (on Android 4.4+) or external program (earlier Android) allows to import user css from places like Dropbox, GDrive or network locations without explicitly downloading css file first. Looks like Kiwix incorrectly implements Android intent for getting content and advertises capabilities that it doesn't actually have. This should be fixed in Kiwix.
