### ISSUE TITLE
Handle links from other applications such as Wikipedia (add intent filters)  

### ISSUE THREAD

**Issue by DFyson** [itkach/aard2-android#50]
Wondering why handling wikipedia links isn't working. Noticed [a commit](https://github.com/itkach/aard2-android/commit/05cdde1d0fd1dc516000dbd5adc287b4c57022db) for handling them but clearly isn't working meanwhile the Wikipedia app handles them fine. This would be a handy feature and has been sought after in [OsmAnd](https://github.com/osmandapp/Osmand/issues/1925).
Using v0.31

**Comment by itkach** [comment]
I'm not sure why is not working for you. Works for me, including from OsmAnd. Which Wikipedias do you have? Are they turned on (toggle in Dictionaries tab, one with book icon)?

**Comment by itkach** [comment]
On a side note, just getting to the "Read Full Article (Online)" button in OsmAnd is 3-4 clicks (4 if there are multiple Wikipedia articles at tapped W pin), and then click on the button and then choosing which program to use (if you don't want to always use Aard 2, which you most likely don't). So that's something like 5-6 clicks to get to the article. To me personally this is useless.

**Comment by DFyson** [comment]
Ohok, I just downloaded a small dictionary file and just assumed Aard2 would still handle the link but then complain it doesn't have the right dictionary installed.

Ya I completely agree about too many clicks to get to the offline wikipedia article, I was nearly about to mention that to to them. I'll add it to this list of [issues](https://github.com/osmandapp/Osmand/issues/2272). I see lots of potential for support among offline apps.
