### ISSUE TITLE
Not available on F-Droid

### ISSUE THREAD

**Issue by maxim-pandra** [itkach/aard2-android#66]
Hey, I didn't manage to find your dictionary on the F-Droid project. There is the old version of aard only.

Is the new version not free or not opensource somehow?

**Comment by itkach** [comment]
It is free and open source. F-Droid, however, requires a clean build from the source and nobody did that. There was an unfinished attempt to get Aard 2 into F-Droid, see https://github.com/itkach/slobber/issues/1. I can assist those who want to get this done, but I am not interested in becoming maintainer of F-Droid package myself.

**Comment by UnderSampled** [comment]
I was the one trying to get it ready for Fdroid. The problem was a binary package (fdroid doesn't accept binary blobs of any sort) in the slobber library. The binary is actuall y a reproducible l, patched version of an open source library, so I thought to simply recompile it on the fly for fdroid. Unfortunately, that library pulls in a lot of other open source libraries, which I didn't know how to confirm for Fdroid's system (they have a list approved repositories, but I guess that one wasn't part of one of those). I can try to find my old fdroid script if you want to take it up again (and if I still have it. It may be simple if you talk with fdroid's devs about how to deal with that other repository.

**Comment by itkach** [comment]
> Unfortunately, that library pulls in a lot of other open source libraries

@UnderSampled I'm not sure why do you say that. [simpleframework](http://www.simpleframework.org/), if that's what we are talking about, doesn't have any external runtime dependencies except junit for tests, as far as I know.

**Comment by itkach** [comment]
@doronbehar Just to clarify, since people keep asking... I have nothing against F-droid and if someone is willing to put it there - great. It's just not something that ```I``` can or want to take on.

**Comment by ildar** [comment]
Right, the prooflink:
https://gitlab.com/fdroid/fdroiddata/issues/863#note_40132915

**Comment by dimqua** [comment]
The app has been added to F-Droid recently.
