### ISSUE TITLE
Feature request: share the link of an entry

### ISSUE THREAD

**Issue by francwalter** [itkach/aard2-android#73]
Hallo
when I open any wikipedia entry in Aard 2 sometimes I need to send the link of the online entry to somebody. But there is no Share-Button. So I open it with my browser and copy the link from the address field of my browser, which is a bit uncomfortable.
Possible to add a way to easy share the link instead of opening it directly with the appropriate intent filter by the system?
Thank

frank

**Comment by francwalter** [comment]
Is this impossible? No reaction at all?

**Comment by itkach** [comment]
It's possible, but would complicate internals more than I'd like. UI code would need to re-parse article's html or cooperate with the embedded browser to fish out article's internal link, which may or may not be there. More trouble than it's worth. When link opens in a browser, instead of copying the link from the address field (which is indeed an awkward interaction that involves long tap over selection) one may use browser's share functionality, which offers a choice of share target apps and a shortcut to most recently used ones.

**Comment by francwalter** [comment]
Maybe I understand: the embedded browser does the linking to the user's browser apps (by intent filter) and **not** Aard2. So to get that link of an article you would need to program something to get it. The embedded browser doesn't support it. Is it like that?

So it is not easy done with a long-press event and then just save the link to the system's clipboard?

**Comment by itkach** [comment]
> Maybe I understand: the embedded browser does the linking to the user's browser apps (by intent filter) and not Aard2. So to get that link of an article you would need to program something to get it.

Yes

> The embedded browser doesn't support it. Is it like that?
It's possible to interact with the browser, but it's rather awkward and adds complexity that I want to avoid.

> So it is not easy done with a long-press event and then just save the link to the system's clipboard?

I don't think there's an easy way to do it

**Comment by francwalter** [comment]
Thank! Understand now and close it.

**Comment by itkach** [comment]
> I don't think there's an easy way to do it

I was wrong, there's WebView api for handling long tap on various elements. 2d841a96f21bd02a85433a81cd89ec07833dc156 

Give it a try: https://github.com/itkach/aard2-android/releases/tag/0.37

**Comment by francwalter** [comment]
YEAHH!!! THANK a lot!!!
Works 👍
