### ISSUE TITLE
[FR] UI option to coalesce articles from multiple dictionaries

### ISSUE THREAD

**Issue by kshpytsya** [itkach/aard2-android#79]
Personally, I find it very convenient the way GoldenDict presents articles for the same word appearing in multiple dictionaries: it coalesces those articles into a single view separated by horizontal bars.

As I understand, technically this can be implemented in three ways:

1. Multiple `WebView` widgets vertically stacked in something like `ScrollView` or `NestedScrollView` (my Android UI development experience is somewhat limited).
2. A single `WebView` with individual articles drawn together as `<iframe>`s.
3. Merge all the articles into a single html.

The third option is mentioned for completeness sake, and, while it is the path taken by GoldenDict, I believe it is really a kludgy one. E.g. GoldenDict rewrites stylesheets to simulate scoping necessary to avoid styles from unrelated dictionaries from interfering. Also, scripts from different dictionaries can interact in unpredictable ways.

The choice between #1 and #2 is not obvious (at least to me) and it may be necessary to prototype both for the sake of comparison.

P.S. Of course, one can simulate this behaviour by preprocessing multiple dictionaries into a single .slob file but this would obviously be significantly less convenient than a proper solution.

**Comment by itkach** [comment]
Aard 2 already coalesces articles with the same title, from multiple or same dictionary. They appear next to each other in word lookup results, and when one of the articles is opened others are available in tabs, in the same order as they appear in lookup result list, just swipe left or right. This is basically your option number 1. I am not sure what do you suggest needs improvement.

**Comment by kshpytsya** [comment]
I am aware of tabs but I, personally, find it much more convenient to have all the articles vertically stacked (just as one has in a paper dictionary), and not having to swipe between them. This especially seems to make sense when the articles are short and may all fit a single screen together.

**Comment by itkach** [comment]
> This especially seems to make sense when the articles are short

Probably, but for Wikipedias and Wiktionaries where most articles are very long this doesn't seem useful at all.


> just as one has in a paper dictionary

Such analogies are of limited utility since paper dictionaries and smartphones are rather different both in information access patterns and in available view (screen, page) real estate.

>  I, personally, find it much more convenient to have all the articles vertically stacked

Lookup result list seems pretty close to the vertical stacking you want, except currently it only shows article title and dictionary and no content. Maybe it can be modified to also show first few words or lines of article content, similar to how GMail or Inbox show beginning of email text after subject.  Would that be a meaningful improvement?

**Comment by kshpytsya** [comment]
> Maybe it can be modified to also show first few words or lines of article content, similar to how GMail or Inbox show beginning of email text after subject. Would that be a meaningful improvement?

This may be a meaningful improvement on its own but, frankly speaking, this would still leave me wanting. I somewhat agree with the rest of your comments, but personally, coming from GoldenDict, navigation and article presentation in Aard2 seems a bit awkward.

The question is if your reluctance to implement this has a technological or political basis, i.e. you don't feel like implementing it because of technical complexity involved, or is it rather because you personally consider it "wrong" way of presenting this information to user. If latter, then I would say "let the user decide" (and maybe use "Google Analytics for Mobile Apps" to analyze the actual usage). If former, then I guess I will have to try implementing this myself.

**Comment by Snaptags** [comment]
This would be very helpful indeed when working with multiple dictionaries! There the "articles" are very short, mostly containing of one word only. It's very cumbersome to have to "open" the "article" just to get the translation.

As a workaround I added the translations to the line itself, improving the view a little bit. But there still is lots of redundant information:
![screenshot](https://user-images.githubusercontent.com/1249745/34436231-ee2bef6e-ec93-11e7-95b6-727a1278c7e1.png)

**Comment by Snaptags** [comment]
Compare this to what an aggregated view could look like :-)

![mock](https://user-images.githubusercontent.com/1249745/34436641-e7c57b46-ec97-11e7-963f-4493fb744820.png)

**Comment by data-man** [comment]
@Snaptags 
Looks good, but how will you choose which article to bookmark?

**Comment by Snaptags** [comment]
Maybe tapping each entry could still open the standard detail view…

**Comment by itkach** [comment]
> coming from GoldenDict, navigation and article presentation in Aard2 seems a bit awkward.

I'm curious, you seem to like how GoldenDict works, why move away from it? 

> navigation and article presentation in Aard2 seems a bit awkward

Doesn't seem awkward to me, but of course I am biased :) Perhaps it's somewhat different from other similar programs, but that's not a bad thing, is it? otherwise it would be very uninteresting :).

Aard 2 is a multi-source dictionary and Wikipedia reader. Dictionaries are typically small, both in number of entries and in content, with little or no markup and navigation. Wikipedias are huge, with lots of large articles with complex styles and formatting and a lot of links, in-page, internal, inter-wiki, and external. I think Aard 2 does a reasonably good job at putting it all together, both for quick lookup and content browsing usage styles. Is it perfect, one true way? Of course not. It's one of possible ways. Can it be tweaked or changed? Of course. However, if something very different is convenient or desirable then different program should be used, or created. 

> The question is if your reluctance to implement this has a technological or political basis, i.e. you don't feel like implementing it because of technical complexity involved, or is it rather because you personally consider it "wrong" way of presenting this information to user. 

I don't think it's a "wrong" way to present information, I just don't see a good way to have it implemented within this particular application and it doesn't look very compelling to me as a general approach. It makes sense for some content, and in fact that's the way content is organized already in some dictionaries, like Wiktionary (by virtue of how content is created, all definitions for all languages go into the same article) or [GCIDE](https://github.com/darkgeek/gcide-converter) (which is a compilation of definitions from various sources). 

So it seems to me that your option 3 ("merge all the articles into a single html") combined with "preprocessing multiple dictionaries into a single .slob file" is actually a pretty good way to do it: .slob file author knows exactly what kind of content they put in, can manipulate it in any way they want, and have complete control over its lookup keys, presentation, markup, style and even javascript to enhance content presentation and interactions within article itself. Aggregate views like in @Snaptags's screenshot above are certainly possible this way (in article view, not in lookup result list). Viewer applications (such as this https://github.com/itkach/aard2-android or https://github.com/itkach/aard2-web) do not have this intimate knowledge of content and do not have the same processing resources (typically running on a mobile or other low-powered device) as a .slob-making program (typically running on a powerful desktop or server). 

> "let the user decide" (and maybe use "Google Analytics for Mobile Apps" to analyze the actual usage). 

I'm not interested in that, sorry. I'm happy to share my work, I appreciate, value and take into account any feedback, but ultimately it's up to the man at the keyboard :) This is a project for fun, not profit, polluting the code-base with irrelevant analytics code is not very appealing. 

> If former, then I guess I will have to try implementing this myself.

You have an itch to scratch, so it seems logical that you should do it yourself :) You have nothing to loose and everything to gain - it can be a valuable experience and you may end up with something useful for yourself.

**Comment by itkach** [comment]
> It's very cumbersome to have to "open" the "article" just to get the translation.

@Snaptags @kshpytsya Sounds like "zero-click" translations may be a separate interesting feature. It's not immediately obvious to me how it might be implemented though. Loading lookup result list would have to also load article content, or rather a portion of it, truncated in some meaningful way. Something to think about.
