### ISSUE TITLE
[FR] intent for CoolReader

### ISSUE THREAD

**Issue by ildar** [itkach/aard2-android#9]
to make Aard2 ready to replace Aard completely

**Comment by dalb8** [comment]
IF you're using an old version of FBReader that is still free software then you can rebuild it referencing aard2's package name, or even try building Aard2 with `sed -i -e '/release {/apackageName "aarddict.android"' build.gradle`.

**Comment by dalb8** [comment]
Tried building Aard2 with the old appId but it doesn't work. The relevant info in FBReader is in assets/dictionaries/main.xml : 

```
<dictionary
                id="Aard Dictionary"
                package="aarddict.android"
                class=".Article"
                action="android.intent.action.SEARCH"
                dataKey="query"
                pattern="%s"
        />
```
but I don't know what to change that to for it to work with Aard2.

**Comment by itkach** [comment]
> The last FBReader version which is FOSS is 1.8.2

It it? FBReader seems alive and well, and as open source as ever: https://github.com/geometer/FBReaderJ, am I missing something?

Source for version with Aard 2 integration is available at https://github.com/itkach/FBReaderJ
(See https://github.com/geometer/FBReaderJ/issues/253 for help with building it)

There's also outstanding pull request to merge this change: https://github.com/geometer/FBReaderJ/pull/314

**Comment by dalb8** [comment]
I tried this change on FBReader tag 1.8.2-ics but no dictionaries are now available and the app crashes when I try to translate a word.

Since 1.8.2 there are non-free jars, lingvo and opendictionary api.

**Comment by dalb8** [comment]
Ah , sorry the change does work. Thanks.

**Comment by dalb8** [comment]
I notice a bug though: if I look up a word from FBReader, then return to FBReader without quitting Aard (e.g. via Recents), then look up another word from FBReader: Aard still shows the first word. However if I quit Aard via the Back button I do get the expected behaviour.

**Comment by itkach** [comment]
> still shows the first word

Indeed. It looks like lookup activity needs to be started with Intent.FLAG_ACTIVITY_CLEAR_TOP , otherwise existing activity is brought to front and doesn't have a chance to handle new intent (because word to lookup is passed in extras and Android doesn't look at extras when filtering/comparing intents).
I updated my FBReader fork: https://github.com/itkach/FBReaderJ/commit/64011cf970ebc98ffb189eca1bba55ba1d423f3d

**Comment by dalb8** [comment]
That's fine now. Can I remark on something tangentially related? Navigating between Aard 2 and FBreader (on OmniRom 4.4.4) via Recents works fine but navigating between Aard 2 and Firefox via Recents doesn't as Aard 2 activity opens instead of Fireside.


-------- Message d'origine --------
De : itkach <notifications@github.com>
Envoyé: 7 juin UTC+01:00
À : itkach/aard2-android <aard2-android@noreply.github.com>
Cc : dalb8 <daithi_black@yahoo.ie>
Objet : Re: [aard2-android] [FR] intent for CoolReader (#9)

> still shows the first word

Indeed. It looks like lookup activity needs to be started with Intent.FLAG_ACTIVITY_CLEAR_TOP , otherwise existing activity is brought to front and doesn't have a chance to handle new intent (because word to lookup is passed in extras and Android doesn't look at extras when filtering/comparing intents).
I updated my FBReader fork: https://github.com/itkach/FBReaderJ/commit/64011cf970ebc98ffb189eca1bba55ba1d423f3d



---

**Comment by dalb8** [comment]
(Please ignore a comment I just deleted). It works fine now. I wonder if it's possible to keep Aard 2 in Recents (whether it was launched from FBReader or not) as it might help jumping back and forward. One can always press the back button but perhaps the app is kept in memory if one doesn't?

**Comment by itkach** [comment]
> I wonder if would be an idea to keep Aard 2 in Recents (whether it was launched from FBReader or not) as it might help jumping back and forward.

I don't see how. And does jumping back and forward really need help :) ?

> perhaps the app is kept in memory if one doesn't

The activity may stay in memory for some time, but next time you look up something you'll get a different one anyway. As for application process itself - I'm not sure being in Recent has any effect on when OS may decide to kill it.

Of course Aard 2 gets on the list of Recent apps when launched from launcher. I thought it made sense to exclude it from Recent when launched as a lookup from another app since in that case it's more of an "extension" of that app rather than an independent application.

**Comment by dalb8** [comment]
It's just that I see different behaviour whether on Omnirom 4.4.4 or CM12. In the latter, based on Android 5, if Aard was called via Firefox, then selecting Firefox in Recents returns me to the website; Aard also appears briefly in Recents. In the former, when I select Firefox, I am still in Aard and thus have to use the back button or go to the home screen to return to Firefox.

**Comment by itkach** [comment]
I'm not sure what behavior are you asking for and how the application is supposed to address navigation quirks in all the various Android flavors that are out there.

**Comment by dalb8** [comment]
It's no big deal. Mainly I thought that navigating via Recents might deserve some extra consideration, particularly since jumping to the previous app is often available as a button shortcut on custom ROMs. Probably, most people have very little need to jump back and forward between dictionary and text many times.

**Comment by dalb8** [comment]
And of course, the History tab retains the last word, if somebody really needs to do that.

**Comment by dalb8** [comment]
CoolReader 3.1.2-68 has refactored the dictionary code and now supports Aard 2.

**Comment by itkach** [comment]
> CoolReader 3.1.2-68 has refactored the dictionary code and now supports Aard 2.

Nice :)
