### ISSUE TITLE
Download dictionary from QR-code

### ISSUE THREAD

**Issue by nikita-moor** [itkach/aard2-android#97]
Our web-site provides several dictionaries in Slob format, and I would like to have a simple way for installing them on users' devices. Current method is download, save to SD card, import into Aard.

Could it be a simple "scan QR-code" and Aard do everything by itself?

I am not experienced in Android development, and cannot say how difficult it is to implement, but this approach is the most user-friendly in my opinion.

**Comment by MHBraun** [comment]
Interesting. Which website do you refer to?
-- 
Sent from my Android phone with WEB.DE Mail. Please excuse my brevity.On 7/24/19, 15:11 Nikita Moor <notifications@github.com> wrote:
Our web-site provides several dictionaries in Slob format, and I would like to have a simple way for installing them on users' devices. Current method is download, save to SD card, import into Aard.
Could it be a simple "scan QR-code" and Aard do everything by itself?
I am not experienced in Android development, and cannot say is it difficult to implement, but this approach is the most user-friendly in my opinion.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/itkach/aard2-android/issues/97?email_source=notifications\u0026email_token=AAYE2S5EPATQDJEGYJDZZALQBCZPLA5CNFSM4IGT2ZMKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HBJWCPA",
"url": "https://github.com/itkach/aard2-android/issues/97?email_source=notifications\u0026email_token=AAYE2S5EPATQDJEGYJDZZALQBCZPLA5CNFSM4IGT2ZMKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HBJWCPA",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by nikita-moor** [comment]
@MHBraun 
[Dictionaries of Latin language](https://nikita-moor.github.io/dictionaries/dictionaries.html)

**Comment by itkach** [comment]
See issues #88 and #89
